### ISSUE TITLE
encountered an panic

### ISSUE THREAD

**Issue by elliotchenzichang** [chenmingyong0423/go-optioner#1]
```
panic: interface conversion: ast.Expr is *ast.SelectorExpr, not *ast.Ident

goroutine 1 [running]:
github.com/chenmingyong0423/go-optioner/options.(*Generator).parseStruct(0x1400005a140, {0x140000282d0, 0xa})
	/Users/zichang.chen/gopath/pkg/mod/github.com/chenmingyong0423/go-optioner@v0.0.4/options/options_generator.go:109 +0x6b8
github.com/chenmingyong0423/go-optioner/options.(*Generator).GeneratingOptions(0x1400005a140)
	/Users/zichang.chen/gopath/pkg/mod/github.com/chenmingyong0423/go-optioner@v0.0.4/options/options_generator.go:70 +0xd8
main.main()
	/Users/zichang.chen/gopath/pkg/mod/github.com/chenmingyong0423/go-optioner@v0.0.4/cmd/optioner/main.go:52 +0x1e8
handler.go:59: running "optioner": exit status 2
```

encountered this panic when I was using this project. Please have a look when you have time. Thanks!

**Comment by chenmingyong0423** [comment]
Can you provide more information, such as the definition of a struct?

**Comment by chenmingyong0423** [comment]
fixed
